npm/template-oss

.github/workflows/ci.yml, lib/content/ci.yml, lib/package.js, package.json
This both removes node 10.0.x and 10.x from the testing matrix, and adds a node engine requirement of `>=12`
=> fix: drop node 10 support

.github/workflows/ci.yml, lib/content/ci.yml
After some discussion it was decided that this was some legacy behavior
in our testing that isn't very applicable to modules, especially
considering that we are planning on omitting package-locks from the git
repos in the near future.
=> fix: remove npm ls -a from ci

README.md, bin/npm-template-check.js, bin/postinstall.js, lib/config.js, lib/content/ci-workspace.yml, lib/postinstall/copy-content.js, lib/postinstall/update-package.js, lib/postlint/check-package.js, package-lock.json, package.json, tap-snapshots/test/postlint/check-package.js.test.cjs, test/bin/npm-template-check.js, test/postinstall/copy-content.js, test/postinstall/update-package.js, test/postlint/check-package.js
* optional configuration to include root and workspaces
* github action for changes in workspace
=> feat: add workspace support

lib/content/ci-workspace.yml
ci-workspace.yml files were setting the script execution to be hardcoded to the libnpmdiff workspace
=> updated workspace ci template to run correct tests

.github/workflows/ci.yml, lib/content/ci-workspace.yml, lib/content/ci.yml
we don't actually do anything differently in these shells since we aren't setting the scriptShell so they're all running in cmd.exe anyway
=> fix: drop bash and powershell from windows ci

.github/workflows/ci.yml, lib/content/ci-workspace.yml, lib/content/ci.yml
i also brought the `ci-workspaces.yml` in sync with the other workflows, but accounting for the workspace related changes. that probably should've been a separate commit but i got a little carried away..
=> fix: try to workaround old npm not being able to update in windows

README.md, lib/postinstall/update-package.js, package.json, tap-snapshots/test/postlint/check-package.js.test.cjs
Currently, the `lint` script will fail on Windows because single quotes are being used to wrap the glob.
This can be easily fixed by using double quotes.
Source: [ESLint CLI doc](https://eslint.org/docs/user-guide/command-line-interface#:~:text=If%20you%20want%20to%20use%20node%20glob%20syntax%2C%20you%20have%20to%20quote%20your%20parameter%20(using%20double%20quotes%20if%20you%20need%20it%20to%20run%20in%20Windows))
=> feat(eslint): support glob for windows

.eslintrc.js, lib/apply/apply-files.js, lib/apply/apply-version.js, lib/apply/index.js, lib/config.js, lib/content/eslintrc.js, lib/content/index.js, lib/content/pkg.json, tap-snapshots/test/apply/full-content.js.test.cjs, tap-snapshots/test/check/diffs.js.test.cjs, test/apply/full-content.js, test/setup.js
- fix: properly apply file changes and version update
this allows individual workspaces to opt out of specific checks, and for the version to be properly updated in package.json even if the rest of the package.json update is not requested
- fix: rm security.md files from workspaces
this file is root only, so it makes sense to delete it from workspaces it if exists
- fix: add root: true to eslint configs
we are using eslint in each workspace, so we always want the `.eslintrc` file to use `root: true` so eslint doesn't traverse into the root and apply those rules
=> fix: misc workspace fixes

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/post-dependabot.yml, lib/content/audit.yml, lib/content/ci.yml, lib/content/index.js, lib/content/npmrc, lib/content/post-dependabot.yml, lib/content/setup-node.yml, tap-snapshots/test/apply/full-content.js.test.cjs, tap-snapshots/test/check/diffs.js.test.cjs
- feat: add audit and fund flags to install
Closes #108
- feat: add lockfile option to control npmrc and ci cache
=> install flags and ci cache

lib/content/release-please.yml, tap-snapshots/test/apply/full-content.js.test.cjs
Temporary workaround for https://github.com/google-github-actions/release-please-action/pull/459
=> fix: explicitly set package-name for release please workspaces

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/post-dependabot.yml, .github/workflows/pull-request.yml, lib/content/setup-git.yml, tap-snapshots/test/apply/full-content.js.test.cjs, tap-snapshots/test/check/diffs.js.test.cjs
I'm not sure if we want to do this, or if there was a reason to keep these bot users separate.
This would change the git user of all our CI commits to @npm-robot. This is the user we use to create PRs to `nodejs/node` (https://github.com/nodejs/node/pull/42550) and add benchmark comments (https://github.com/npm/cli/pull/4716#issuecomment-1093774243).
=> fix: use ops+robot as git user for all ci

lib/check/check-changelog.js, lib/util/get-git-url.js
os.EOL is \r\n in win32, which means this check is pretty much guaranteed to fail in windows
=> fix: compare to \n instead of os.EOL

package.json
yaml@2.0.0 or greater depends on node@14 while 2.0.0-11 still works in node 12. for now, i pinned our version here so we don't get CI failures in node 12. we'll probably be able to revert this once we raise our low bar to node 14
=> fix: pin yaml to 2.0.0-11

lib/check/check-changelog.js, lib/check/check-gitignore.js, lib/util/parser.js
we should only ever write files with a `\n` line ending, even in windows. let's stop doing the platform specific thing and be general so we can stop getting hard to trace issues in windows
=> fix: remove more usage of os.EOL

lib/content/audit.yml, lib/content/ci.yml, lib/content/codeql-analysis.yml
This will help these checks run a few hours before Statusboard and be up to date for morning in Pacific Time.
=> feat: make cron workflows run early PT

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/post-dependabot.yml, .github/workflows/pull-request.yml, .github/workflows/release-please.yml, .github/workflows/release.yml, lib/content/_setup-job-matrix.yml, lib/content/_setup-job.yml, lib/content/audit.yml, lib/content/post-dependabot.yml, lib/content/pull-request.yml, lib/content/release-please.yml, lib/content/release.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/diff-snapshots.js.test.cjs
This adds a `if: github.repository_owner == 'npm'` to each workflow so
they don't run outside of the npm organization by default.
Closes #182
=> fix: dont run workflows outside of npm org

.github/workflows/codeql-analysis.yml, lib/content/codeql-analysis.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs
v1 of codeql is being deprecated in december: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> feat: update codeql actions to v2

.github/workflows/post-dependabot.yml, lib/content/post-dependabot.yml, tap-snapshots/test/apply/full-content.js.test.cjs, tap-snapshots/test/apply/source-snapshots.js.test.cjs
When we ship `engines` changes we will release a semver major update
to template-oss, and the resulting dependabot PRs will get a `feat!`
commit to indicate that they will all need major releases as well.
This also updates the workflow to attempt to commit a subset of the
applied changes, without the workflows. The workflow will still fail, if
any changes were not committed but this allows us to have the proper
conventional commit message in the git history that we can amend when
fixing these PRs manually.
=> feat: make template-oss postinstall commit a breaking change for majors

.github/workflows/post-dependabot.yml, lib/content/post-dependabot.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs
This is so it work with the workspace flag we call with it
=> fix: remove leading slash from dependabot metadata dir

.github/workflows/audit.yml, lib/content/_step-audit.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/diff-snapshots.js.test.cjs
This still runs `audit` on all deps but will only report the errors and
not fail CI.
=> feat: only fail on production `audit`

.github/workflows/pull-request.yml, lib/content/pull-request.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs
the quotes are necessary here because a pr title (and a base_ref) could have characters in them that bash tries to evaluate, to prevent that i wrapped them in single quotes
=> fix: wrap pr title and base_ref in quotes

.github/workflows/release.yml, bin/release-please.js, lib/content/release.yml, lib/release-please/index.js, tap-snapshots/test/apply/source-snapshots.js.test.cjs
This adds logging to the release-please workflow step to get a better idea of what is causing some of the transient failures we've seen in that job.
Ref https://github.com/npm/stafftools/actions/runs/4109009588/jobs/7090345220#step:8:121
Ref https://github.com/npm/cli/actions/runs/4071227938/jobs/7012840616#step:6:805
=> Add logging and dispatch to rerun release workflows on tagged releases

.github/workflows/post-dependabot.yml, .github/workflows/release.yml, lib/content/post-dependabot.yml, lib/content/release.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for more info
=> fix: remove deprecated set-output in favor of GITHUB_OUTPUT

bin/release-manager.js
the previous usage of backticks for subshells works in bash and zsh, but not fish. switching to the `$()` syntax works in all three shells
=> fix: use a more portable means of spawning subshells

test/setup.js
currently running the tests creates git repos and commits using your default git configuration. for me personally, this means that i get a popup confirming the signing request for these commits since i have my git configured to always sign. this means when running tests, i get a lot of notifications. by forcibly telling git to _not_ sign these commits, this no longer happens, and since signatures are not important for test fixtures that are being discarded anyway felt like a quick usability win here.
=> chore: do not sign commits in tests

.github/settings.yml, lib/content/index.js, lib/content/settings.yml, tap-snapshots/test/apply/files-snapshots.js.test.cjs, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/snapshots.js.test.cjs
this settings file is intended to setup our merge strategy as well as branch protections, and is the first step in maintaining repo settings as code.
in order for this file to take effect, the probot settings app must be installed and enabled for the repo: https://github.com/apps/settings
for #98
=> feat: add probot settings template

.gitignore, CONTRIBUTING.md, lib/content/CONTRIBUTING.md, lib/content/index.js, tap-snapshots/test/apply/files-snapshots.js.test.cjs, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/snapshots.js.test.cjs
This is a pared down version of the cli CONTRIBUTING.md
=> feat: add CONTRIBUTING.md

.github/workflows/ci-test-workspace.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, lib/config.js, lib/content/index.js, lib/content/pkg.json, lib/content/release.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/diff-snapshots.js.test.cjs, test/apply/engines.js, test/apply/eslint.js
This PR contains the following commits which add config options to make landing template-oss easier in older packages.
- feat: add release/v branches to all branch CI
- feat: add config option to not update npm
- feat: add config option to disable eslint
- feat: allow adding latest to other ci versions
=> Features for landing template-oss in older packages

lib/apply/apply-files.js, lib/check/check-apply.js, lib/config.js, lib/util/files.js, lib/util/merge.js, lib/util/parser.js, package.json, test/apply/overwrite-false.js
This PR contains two commits:
1. Makes file parsers based on the target filename instead of the source filename. This better matches the expected behavior since the target filename is usually standard (like `package.json` or `.gitignore`) but the source often needs to be named differently to avoid issues with those well known filenames.
2. By default template-oss allows for written files to be configured on a per-repo basis. This is helpful for different repos to create their own templated files and apply those. With this change, a repo can now set `overwrite: false` to a templated file and have those updates be applied after the default template-oss changes are made.
=> Add `overwrite:false` file config and better parser matching

.github/settings.yml, lib/content/settings.yml, tap-snapshots/test/apply/source-snapshots.js.test.cjs
Now that we use a wildcard to match against release branches for
backports, creation of those branches should also be locked down to
admins only.
=> fix: block protected branch creations

.github/workflows/audit.yml, .github/workflows/ci-release.yml, .github/workflows/ci-test-workspace.yml, .github/workflows/ci.yml, .github/workflows/post-dependabot.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, lib/content/_step-node.yml, lib/content/index.js, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/diff-snapshots.js.test.cjs
Fixes #353
This removes the `npmSpec` config in favor of installing an npm major based on the node version.
This will help us get more CI running npm@10 for older packages that only support npm@10 in some CI versions.
=> fix: install npm in CI based on node version

.github/workflows/release.yml, lib/config.js, lib/content/_job-release-integration.yml, lib/content/ci-release.yml, lib/content/index.js, lib/util/git.js, test/apply/release.js
=> feat: set backport release from config instead of current branch

lib/config.js, lib/content/index.js, test/apply/npm-bin.js
This will fix the issue in npm/cli where we want to run older npm versions for some workspaces.
=> fix: allow overriding path to npm bin in workspaces

lib/util/git.js
=> fix: prefer upstream over origin when getting remote

README.md
This has always been true for this package, but we haven't made too many API breaking changes. Recently #362 landed which is a breaking change, since the API includes shadowing and using these files as partials. So it is best to embrace these types of changes and document the behavior.
=> docs: add note about semver and breaking changes

.github/workflows/release-integration.yml, .github/workflows/release.yml, lib/content/_job-release-integration-yml.hbs, lib/content/release-integration-yml.hbs, lib/content/release-yml.hbs
Since it is now invoked by `workflow_call` the permissions need to be set by both the caller and callee.
This also only forwards the necessary PUBLISH_TOKEN secret to the workflow instead of all secrets.
The above two things are only applied when `publish: true` is set.
=> fix: give release integration workflow correct permissions and secrets

lib/release/release-manager.js
This also fixes the release manager logging since `core.info` only allows a single string argument.
These changes are not tested because they are all tested in #334. But I wanted to fix this bug before that gets reviewed.
=> fix: fallback to default release process of 404 from hosted version

.github/workflows/release-integration.yml, lib/content/_job-release-integration-yml.hbs, tap-snapshots/test/apply/source-snapshots.js.test.cjs
This fixes an issue where single quotes within releases were not escaped.
Copied directly from https://github.com/npm/proc-log/pull/79
=> fix: iterate over releases from env var

lib/release/changelog.js, test/release/changelog.js
This is tested with mocked commits within `template-oss` because it's still hard to test this  kind of stuff intergration style with `release-please`.
I did manually run this code against https://github.com/npm/npm-cli-release-please and for two PRs with the `postinstall for dependabot template-oss` commit message, only one made it to the changelog. https://github.com/npm/npm-cli-release-please/pull/246
Screenshots since any links to that repo might change due to other tests. Note that only PR `#274` is in the changelog and not `#273`.
=> fix: only use latest template-oss specific commits in changelog

lib/content/index.js, lib/release/changelog.js, release-please-config.json, tap-snapshots/test/apply/source-snapshots.js.test.cjs, test/release/changelog.js
In #378 we decided to make template-oss rebuild PRs for chore commits to solve the problem of needing to manually recreate PRs after pushing a chore that affected the release process.
This was a good change but had the side effects of:
- Creating noise in the `Chores` sections of the changelog for repos that don't get released often but landed a lot of template-oss updates between releases. This was greatly reduced in #430
- Creating release PRs in repos that didn't need an actual release because it was only chore commits. This PR fixes this by only creating a PR if there is at least one non-chore commit. This will continue to work around the original problem of updating pending releases for new chore commits, but won't open PRs for chores only.
As a side effect of this I removed the code …
=> fix: dont create chore only PRs

.github/workflows/release-integration.yml, lib/content/_job-release-integration-yml.hbs, tap-snapshots/test/apply/source-snapshots.js.test.cjs
=> fix: get correct exit code from npm publish/view

.github/workflows/ci-release.yml, .github/workflows/ci-test-workspace.yml, .github/workflows/ci.yml, lib/content/_job-matrix-yml.hbs, lib/util/template.js, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/diff-snapshots.js.test.cjs
`macos-latest` recently switch to M1s which don't have Node builds for v14 and below. This change adds both macos-latest and macos-13 (which uses x86 cpus) and then excludes one or the other based on the Node version in the matrix. The result is still only one macOS CI job per Node version, but it will now use the correct CPU architecture per version.
=> feat: use macos-(latest|13) based on node version

lib/check/check-apply.js, lib/util/files.js, lib/util/parser.js, test/apply/overwrite-false.js
=> fix: properly check for diff with multiple files from overwrite:false

package.json, workspace/test-workspace/package.json
- chore: bump @npmcli/template-oss to 4.22.0
- chore: postinstall for dependabot template-oss PR
=> chore: bump @npmcli/template-oss to 4.22.0

lib/content/_job-release-integration-yml.hbs, package.json, tap-snapshots/test/apply/source-snapshots.js.test.cjs
If `publish: true` is not set, then the release intergration workflow falls back to running `npm view $SPEC` which will error if the package has not been published. This tags the CODEOWNERS in the release issue so we know something went wrong.
This doesn't have much use now that we are moving everything to `publish: true` but it would have caught a missing publish last week that I missed on `@npmcli/fs`: https://github.com/npm/fs/actions/runs/8946801618/job/24577963034#step:7:4
The `RELEASES` env var was only being set for the publish step, not the check if published step.
=> fix: pass releases to publish check

.github/actions/create-check/action.yml, .github/actions/install-latest-npm/action.yml, .github/workflows/post-dependabot.yml, SECURITY.md, lib/content/SECURITY-md.hbs, lib/content/action-create-check-yml.hbs, lib/content/action-install-latest-npm-yml.hbs, lib/content/post-dependabot-yml.hbs, lib/util/dependabot.js, tap-snapshots/test/apply/source-snapshots.js.test.cjs
`steps.metadata.outputs.directory` is set to `/main`, not `/`, when `package.json` is at the root of the repository. I suspect adding `target-branch` to `dependabot.yml` (#330) added a `main` segment to Dependabot PR branch names, which changed the value of `steps.metadata.outputs.directory`.
By fixing this issue, we shouldn't need to routinely use stafftools to fix up template-oss Dependabot PRs. 🤞🏼 
I couldn't quickly find a `bump @npmcli/template-oss` Dependabot PR for a workspace to inspect `steps.metadata.outputs.directory` and fix workspaces support. If that's important, we may want to either enable Dependabot for `npm/cli` or create a separate `template-oss-test` repo. It's not clear if Dependabot will create a PR for `workspace/test-workspace` upon our next release.
The first PR …
=> fix: Use `include-workspace-root` for `/main` in Post Dependabot

.commitlintrc.js, lib/content/commitlintrc-js.hbs, tap-snapshots/test/apply/source-snapshots.js.test.cjs
A breaking change footer like the one below is over 100 characters, resulting in commitlint CI failures.
```
BREAKING CHANGE: `ssri` is now compatible with the following semver range for node: `^16.13.0 || >=18.0.0`
```
Example CI failure: https://github.com/npm/ssri/actions/runs/10169599799/job/28126863705#step:7:12
Associated PR: https://github.com/npm/ssri/pull/137
=> fix: Don't restrict length for commit message footer

lib/content/package-json.hbs
Working on getting tap21 to work.  These are the changes needed to get
`npm/statusboard` working properly.
=> More tap 21 fixes

lib/release/changelog.js
release-please will re-inject the entire changelog when looking
for the existing dependencies section in some cases. Have multiple
newlines between sections of the changelog triggers that behavior
because it looks for lines that do no start with '*' but it does
not account for empty lines
=> fix: no duplicate changelog entries

lib/release/release-please.js, lib/release/semver-versioning-strategy.js, test/release/version.js
`prereleases` do not work in release-please, i'm seeing the inability to get a repo into or out of `prerelease` mode, (where the packages have tags in the versions ie. `-pre-0` at the end).
* I was unable to get a repo *into* prerelease using the latest version of release-please on my personal project `reggi/packages`.
* And the `npm/cli` has been stuck in prerelease mode. It was able to get itself into prerelease because of the wrapper around release-please we have in this repo. (trail: [npm/cli workflow](https://github.com/npm/cli/blob/latest/.github/workflows/release.yml#L54), [Strategy Turnery](https://github.com/npm/template-oss/blob/abdc9398f47d4761d589617235bee0fdb4827128/lib/release/release-please.js#L56))
I do not believe release please has this `options.prerelease ternary …
=> fix:  correct versions with prereleases

.github/workflows/ci-release.yml, .github/workflows/ci.yml, lib/util/import-or-require.js, package.json, test/apply/esm.js, test/apply/import-or-require.js
prereq for https://github.com/npm/template-oss/pull/498
=> feat: engines to ^20.17.0 || >=22.9.0

.github/workflows/ci-release.yml, .github/workflows/ci.yml, lib/content/package-json.hbs, lib/release/node-workspace-format.js, lib/release/release-manager.js, lib/release/release-please.js, lib/release/semver-versioning-strategy.js, lib/util/import-or-require.js, package.json, tap-snapshots/test/apply/files-snapshots.js.test.cjs, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/bin/check.js.test.cjs, tap-snapshots/test/check/diff-snapshots.js.test.cjs, tap-snapshots/test/check/snapshots.js.test.cjs, tap-snapshots/test/release/release-manager-mock-release-manager.js.test.cjs, tap-snapshots/test/release/release-manager-npm-cli.js.test.cjs, tap-snapshots/test/release/release-manager-prerelease.js.test.cjs, tap-snapshots/test/release/release-manager-publish-and-lockfile.js.test.cjs, tap-snapshots/test/release/release-manager-single-release.js.test.cjs, tap-snapshots/test/release/release-manager-workspace-names.js.test.cjs, test/apply/esm.js, test/apply/tap.js, test/bin/apply.js, test/bin/check.js, test/check/snapshots.js, test/fixtures/mock-release.js, test/setup.js
Resurfaces an old PR that updated tap 16 -> 19 (still not sure what's needed from that until i see the diff. 
Had to do some googling to find why `/* istanbul ignore next */` doesn't work anymore.
https://github.com/tapjs/tapjs/issues/1027
got some node 22
failures - ENOENT: no such file or directory, open '/home/runner/work/template-oss/template-oss/.tap/fixtures/test-apply-esm.js-basic/file.js'
doesn't work on 20.5.0 because of https://github.com/tapjs/tapjs/pull/1028
=> deps: tap@21.0.1

lib/content/package-json.hbs
before 
```
"exclude": [
"docs/**,smoke-tests/**,mock-globals/**,mock-registry/**,workspaces/**"
]
```
after
```
"exclude": [
"docs/**",
"smoke-tests/**",
"mock-globals/**",
"mock-registry/**",
"workspaces/**"
],
```
=> fix: tap exclude

.gitignore, lib/content/index.js, tap-snapshots/test/apply/source-snapshots.js.test.cjs, tap-snapshots/test/check/snapshots.js.test.cjs, workspace/test-workspace/.gitignore
https://github.com/npm/documentation/pull/1518 the github eslint plugin is now esm only in 6.0.0. We need to be able to add an eslint.config to adapt.
=> chore: allow eslint.config.js in npm project gitignore files

lib/content/dependabot-yml.hbs, lib/content/index.js, lib/util/dependabot.js, test/apply/dependabot.js
This pull request introduces enhancements to the Dependabot configuration system, focusing on adding support for customizable update schedules at both global and branch-specific levels. It also includes updates to the test suite to ensure comprehensive coverage of these new features.
=> feat: Add `dependabotInterval` configuration
